# Generated by Django 4.2.16 on 2024-11-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('PR', 'Proposed'), ('CO', 'Confirmed'), ('CA', 'Cancelled'), ('DO', 'Done')], default='PR', max_length=2)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('cost_per_player', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cost_per_car', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('number_of_cars', models.IntegerField()),
                ('cost_extras', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_play', models.ManyToManyField(to='gigger.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingAtGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigger.gig')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigger.instrument')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigger.player')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='required_instruments',
            field=models.ManyToManyField(to='gigger.instrument'),
        ),
        migrations.CreateModel(
            name='AvailabilityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('AV', 'Available'), ('IF', 'If needs be'), ('UN', 'Unavailable')], default='UN', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigger.gig')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigger.player')),
            ],
        ),
    ]
