# Generated by Django 4.2.16 on 2024-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='number_of_cars',
            field=models.IntegerField(default=0),
        ),
    ]
