# Generated by Django 4.2.16 on 2024-11-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0002_alter_gig_number_of_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='number_of_charging_players',
            field=models.IntegerField(default=7),
        ),
    ]
