# Generated by Django 4.2.16 on 2024-11-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0004_gig_handled_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilityresponse',
            unique_together={('gig', 'player')},
        ),
    ]
