# Generated by Django 4.2.16 on 2024-11-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0005_alter_availabilityresponse_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playingatgig',
            unique_together={('gig', 'instrument')},
        ),
    ]
