# Generated by Django 4.0.6 on 2024-11-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0006_alter_playingatgig_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='icon',
            field=models.CharField(default='?', max_length=5),
        ),
    ]
