# Generated by Django 4.0.6 on 2024-11-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0007_gig_start_time_instrument_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='handled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigger.player', verbose_name='Band contact'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Dancing start time'),
        ),
    ]
