# Generated by Django 4.0.6 on 2024-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigger', '0009_alter_gig_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='required_instruments',
            field=models.ManyToManyField(null=True, to='gigger.instrument'),
        ),
    ]
